version: '3.4'

services:
  app:
    build:
      context: .
    ports:
      - "5001:5001"

    environment:
      - MONGO_DB_LINK=mongodb+srv://AngadRajSingh:root@cluster0.ogdrv.mongodb.net/?retryWrites=true&w=majority
      - PORT=5001
      - JWT_TOKEN=dserfoefenfiefneifnefnjklskowwoercvnfbe8213